unstable_features = true
reorder_impl_items = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
use_try_shorthand = true
use_field_init_shorthand = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
