name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-macos:
    name: Build for macOS
    runs-on: macos-latest
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v6
      - run: brew install xmake m4 automake autoconf libtool
      - run: xmake f -m release -a arm64 -y && xmake -y
      - uses: actions/upload-artifact@v7
        with:
          name: macOS Release (arm64)
          path: build/macosx/arm64/release/PanicInfoReader
      - run: xmake f -m release -a x86_64 -y && xmake -y
      - uses: actions/upload-artifact@v7
        with:
          name: macOS Release (x86_64)
          path: build/macosx/x86_64/release/PanicInfoReader
      - run: xmake f -m debug -a arm64 -y && xmake -y
      - uses: actions/upload-artifact@v7
        with:
          name: macOS Debug (arm64)
          path: build/macosx/arm64/debug/PanicInfoReader
      - run: xmake f -m debug -a x86_64 -y && xmake -y
      - uses: actions/upload-artifact@v7
        with:
          name: macOS Debug (x86_64)
          path: build/macosx/x86_64/debug/PanicInfoReader

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get install xmake m4 automake autoconf libtool
      - run: xmake f -m release -y && xmake -y
      - uses: actions/upload-artifact@v7
        with:
          name: Linux Release (x86_64)
          path: build/linux/x86_64/release/PanicInfoReader
      - run: xmake f -m debug -y && xmake -y
      - uses: actions/upload-artifact@v7
        with:
          name: Linux Debug (x86_64)
          path: build/linux/x86_64/debug/PanicInfoReader

  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v6
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - run: xmake f -m release -y && xmake -y
      - uses: actions/upload-artifact@v7
        with:
          name: Windows Release (x64)
          path: build/windows/x64/release/PanicInfoReader.exe
      - run: xmake f -m debug -y && xmake -y
      - uses: actions/upload-artifact@v7
        with:
          name: Windows Debug (x64)
          path: build/windows/x64/debug/PanicInfoReader.exe
