name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-macos:
    name: Build for macOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - run: xmake f -m release -a arm64 -y && xmake -y
      - uses: actions/upload-artifact@v7
        with:
          name: macOS Release (Apple Silicon)
          path: build/macosx/arm64/release/PanicInfoReader
      - run: xmake f -m debug -a arm64 -y && xmake -y
      - uses: actions/upload-artifact@v7
        with:
          name: macOS Debug (Apple Silicon)
          path: build/macosx/arm64/debug/PanicInfoReader
      - run: xmake f -a x86_64 -y && xmake -y
      - uses: actions/upload-artifact@v7
        with:
          name: macOS Release (Intel)
          path: build/macosx/x86_64/release/PanicInfoReader
      - run: xmake f -m debug -a x86_64 -y && xmake -y
      - uses: actions/upload-artifact@v7
        with:
          name: macOS Debug (Apple Silicon)
          path: build/macosx/x86_64/debug/PanicInfoReader

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - run: xmake f -m release -y && xmake -y
      - uses: actions/upload-artifact@v7
        with:
          name: Linux Debug
          path: build/linux/x86_64/debug/PanicInfoReader
      - run: xmake f -m debug -y && xmake -y
      - uses: actions/upload-artifact@v7
        with:
          name: Linux Release
          path: build/linux/x86_64/release/PanicInfoReader

  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - run: xmake f -m release -y && xmake -y
      - uses: actions/upload-artifact@v7
        with:
          name: Windows Debug
          path: build/windows/x86_64/debug/PanicInfoReader
      - run: xmake f -m debug -y && xmake -y
      - uses: actions/upload-artifact@v7
        with:
          name: Windows Release
          path: build/windows/x86_64/release/PanicInfoReader
